test: testing...

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,8 +15,8 @@ jobs:
     - name: Echo build start
       run: echo "🚀 Starting build process..."
     
-    - name: Simulate failure
-      run: exit 1
+    #- name: Simulate failure
+    #  run: exit 1
     
     - name: Echo build complete
       run: echo "✅ Build completed successfully!"
