ci: run ubuntu-latest if self-hosted-linux fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,20 +9,17 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     timeout-minutes: 1
-    continue-on-error: true
     steps:
     - uses: actions/checkout@v3
     
     - name: Echo build start
       run: echo "🚀 Starting build process..."
-    - name: Error step
-      run: |
-        rm test.php
+
   test:
     name: Test
     runs-on: ubuntu-latest
     needs: build
-    if: ${{always() && (needs.build.result == 'failure' || needs.build.result == 'cancelled')}}
+    if: always() && (needs.build.result == 'failure' || needs.build.result == 'cancelled')
     steps:
     - uses: actions/checkout@v3
     
@@ -41,3 +38,18 @@ jobs:
       run: |
         echo "✅ Forcing workflow success..."
         exit 0
+  finalize:
+    name: Finalize Workflow
+    runs-on: ubuntu-latest
+    needs: [build, test]
+    if: ${{ always() }}  # Siempre se ejecuta
+    steps:
+    - name: Check final status
+      run: |
+        if [ "${{ needs.test.result }}" == "success" ] || [ "${{ needs.build.result }}" == "success" ]; then
+          echo "✅ Marking workflow as success"
+          exit 0
+        else
+          echo "❌ Workflow failed"
+          exit 1
+        fi
